### ISSUE TITLE
5.2 Installation Error - MySql Syntax Error

### ISSUE THREAD

**Issue by patrickmau** [orangehrm/orangehrm#1521]
**Environment details**
OrangeHRM version: 5.2 - fresh install
OrangeHRM source: Sourceforge
Platform: Linux ip-111-222-333-444 5.4.0-1018-aws #18-Ubuntu SMP Wed Jun 24 01:15:00 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
PHP version: PHP 7.4.3 (cli) (built: Aug 17 2022 13:29:56) ( NTS )
Database and version: MySQL 8.0.31-0ubuntu0.20.04.1 (Ubuntu)
Web server: Apache2

**Describe the bug**
Note: I am running in MySQL 8 which is not officially supported, changes were made to `/installer/config/sytem_requirements.php` to pass validation.

Problem:
When trying to install the latest OpenSource OrangeHRM v5.2, I am unable to complete installation for step "Applying database changes" with the following error in the log:

[2022-11-06T16:11:21.947268+00:00] installer.ERROR: An exception occurred while executing a query: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'groups WHERE groups.name = 'help' ORDER BY id DESC' at line 1 [] []
 
**To Reproduce**
Run 5.2 fresh installation routine.

**Expected behavior**
Complete installation

**What do you see instead:**
Process fails at 99% during step "Applying database changes"

**Additional context**
I am running 4.1 on production, made a copy and tried to install 5.2 via "update to 5.2" instead, resulting in the same error.

**Comment by RajithaKumara** [comment]
Hi @patrickmau ,
Thanks for explaining the issue in detail.
 We are working on supporting MySQL 8.0. Most probably it will be addressed in 5.3 release (hopefully will be released end of this year).

For the moment as a patch you can follow below steps:

### 1. Fix 5.2 migration

Go to `installer/Migration/V5_2_0/Migration.php` and find; (check the code diff [here](https://github.com/orangehrm/orangehrm/pull/1506/files#diff-e5e137f8677c1aef7ecb3f919b0e9846797b77a2a4b954a672eaff6d3871bd72))
```php
// line no 352
        $qb = $this->createQueryBuilder()
            ->select('groups.id')
            ->from('ohrm_i18n_group', 'groups')
            ->andWhere('groups.name = :name')
            ->setParameter('name', 'help')
            ->addOrderBy('id', 'DESC');
```

and replace with
```php
        $qb = $this->createQueryBuilder()
            ->select('ohrm_i18n_group.id')
            ->from('ohrm_i18n_group')
            ->andWhere('ohrm_i18n_group.name = :name')
            ->setParameter('name', 'help')
            ->orderBy('ohrm_i18n_group.id', 'DESC');
```


### 2. Disable ONLY_FULL_GROUP_BY
If `sql_mode`, `ONLY_FULL_GROUP_BY`  [enabled by default](https://dev.mysql.com/doc/refman/5.7/en/sql-mode.html#sqlmode_only_full_group_by) please disable it. ([StackOverflow](https://stackoverflow.com/questions/23921117/disable-only-full-group-by), [OrangeHRM CI](https://github.com/orangehrm/orangehrm/blob/5.3/.github/workflows/scheduled_test.yml#L66))
Otherwise, you will see an unexpected error in the dashboard.

```sql
SET GLOBAL sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY',''));
```
> **Warning**
> Please not that if the database server contains more applications (other DBs), make sure to check their requirements also. Otherwise other application may break.



For the moment those are the issues we identified with MySQL 8.0 support.

**Comment by patrickmau** [comment]
Thank you, this at last allowed me to install the app.

**Comment by RajithaKumara** [comment]
MySQL 8.0 is officially supported in OrangeHRM 5.3. Get the latest build [here](https://sourceforge.net/projects/orangehrm/).
