### ISSUE TITLE
Skip installation in docker

### ISSUE THREAD

**Issue by KremlinGhost** [orangehrm/orangehrm#1662]
I successfully completed the first installation of OrangeHRM running in docker. Everything is working great, but I would like to know if there is some way to skip the re-install/update if it fails?

I already tried to put the completed config with the correct permissions along the path:
/var/www/html/lib/confs/Conf.php
But it didn't work.

I went through your documentation but didn't find any information where it was mentioned. I apologize if I was inattentive. Thanks for your help.

**Comment by mukundshah** [comment]
@Super-Chama any update on this?

**Comment by devishke-orange** [comment]
Hi @mukundshah and @KremlinGhost 

Are you restoring the database as well? If you don't do that then the system won't work. What you can do is make a backup of your database immediately after a fresh install so that you can restore it when you want to do a quick reinstall.

I replicated this process using our OrangeHRM docker container and a MariaDB 10.11.4 container. I installed the system and immediately made a backup of my `Conf.php` and database (`mysqldump -uuser -ppassword dbname > backup.sql`). Please watch the attached video.

[Screencast from 2023-12-07 09:19:59.webm](https://github.com/orangehrm/orangehrm/assets/97493184/890e4b68-a287-44cf-8d51-48feb6373769)

**Comment by mukundshah** [comment]
Hi @devishke-orange 

Thank you for your help.

What I did is, I copied Conf.php from local to the docker image. And it skips the install step totally.

**Comment by devishke-orange** [comment]
I'm closing this as the question has been answered.
