### ISSUE TITLE
Is it possible to make fork repository private or only public is possible?

### ISSUE THREAD

**Issue by jstawow** [orangehrm/orangehrm#1756]
### OrangeHRM version

5.5

### Environment details

- OrangeHRM source:
- Platform:
- PHP version:
- Database and version:
- Web server:
- Browser:

### Describe the bug

Why my fork-repo is public, is it possible to make it private?

**Comment by jstawow** [comment]
<img width="1005" alt="Zrzut ekranu 2023-10-13 o 07 08 43" src="https://github.com/orangehrm/orangehrm/assets/91880075/b652ee2e-10c6-4013-9c62-c44c7ea0c106">

**Comment by devishke-orange** [comment]
Hi @jstawow 

I'm sorry for the late response. According to GitHub's documentation this is not allowed: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/about-permissions-and-visibility-of-forks#about-visibility-of-forks

I will close this since nothing can be done from our end.
