### ISSUE TITLE
Different version/functionality on orangehrm.com and Github

### ISSUE THREAD

**Issue by alexbash7** [orangehrm/orangehrm#1829]
**Is your feature request related to a problem? Please describe.**
Hi there, 

I initially registered to check your system on orangehrm.com, and after installing of latest release from Github I found that there is different functionality. Is it different versions on orangehrm.com and Github? Or I miss some settings when installed. Thank you

**Comment by devishke-orange** [comment]
Hi @alexbash7 

What is the difference you are seeing?

**Comment by alexbash7** [comment]
Hi @devishke-orange

Please find attached screenshot of main menu from orangehrm.com and Github version below. They are lot of menu items missing in Github version like: HR Administration, Employee Management, Reports and Analytics, On/Of boarding,etc. They look like totally different versions. 

![SCR-20240328-pmfe](https://github.com/orangehrm/orangehrm/assets/45295853/476351bf-e9e2-4253-9913-809a459efed5)

**Comment by devishke-orange** [comment]
Oh, I see the confusion. The version you are seeing on our website is OrangeHRM Advanced. The version we offer on GitHub is OrangeHRM Starter.

Here's the page for OrangeHRM Starter on our website: https://orangehrm.com/en/orangehrm-starter-open-source-software/

If you are interested in OrangeHRM Advanced you can sign up for a free trial here: https://www.orangehrm.com/en/30-day-free-trial/

Thanks for reporting this. We'll take a look into how we can improve the website so that information is clearer. I'll close this issue for now.
