### ISSUE TITLE
insulation issue 

### ISSUE THREAD

**Issue by a-j-n** [orangehrm/orangehrm#238]
I get this in DB install 
<img width="894" alt="screen shot 2018-06-11 at 11 08 57 pm" src="https://user-images.githubusercontent.com/34508885/41257407-0234223c-6dcd-11e8-9633-8f522717e133.png">

**Comment by samanthajayasinghe** [comment]
@a-jamal What is the mysql and php version that you installed?

**Comment by a-jamal** [comment]
@samanthajayasinghe 
and[ laravel valet](https://laravel.com/docs/5.6/valet) as  web server 
<img width="605" alt="screen shot 2018-06-13 at 4 58 36 pm" src="https://user-images.githubusercontent.com/34508885/41359575-15aa9a1c-6f2b-11e8-9b8d-fdd5c6711985.png">

**Comment by kavithagurusamy** [comment]
@ivanlinares 
Are you still having the issue or you are able to install the instance?

**Comment by gmipf** [comment]
I had the same issue until yesterday. You need to set the bind-address in my.cnf to 0.0.0.0 or 127.0.0.1. On my default installation of mariadb 10.2 the server always wanted to listen to an IPv6 address. 
After that you need to use 127.0.0.1 as server instead of localhost in the orangehrm installation wizard. If you have selinux set to enforcing, you need to allow rw access to httpd (apache), allowing scripts and allowing db connections to httpd. 

Here are some commands for selinux in CentOS 7:

chcon -t httpd_sys_rw_content_t /var/www/html/ -R
chcon -t httpd_sys_script_exec_t /var/www/html/ -R
setsebool -P httpd_can_network_connect 1
setsebool -P httpd_can_network_connect_db 1

And you need to setup firewalld properly, but I have disabled it.
