### ISSUE TITLE
PHP Fatal error:  Call to a member function getFullName()

### ISSUE THREAD

**Issue by trongnghia203** [orangehrm/orangehrm#444]
Dear OrangeHRM, @all,

I am looking for help with this issue. It seems like OrangeHRM loss the css, but only on this page.

Thank you very much for attention on my issue.
Nghia

symfony/log/orangehrm.log
`[04-Jan-2019 02:34:19 America/New_York] PHP Fatal error:  Call to a member function getFullName() on a non-object in /var/www/orangehrm-3.3.3/orangehrm-3.3.3/symfony/lib/model/doctrine/orangehrmRecruitmentPlugin/JobVacancy.class.php on line 29
`
![image](https://user-images.githubusercontent.com/17697663/50677824-8d7f9700-102e-11e9-892b-8232bee839bd.png)

**Comment by kavithagurusamy** [comment]
@trongnghia203 
This issue was fixed from OrangeHRM 4.1.1 version. Install / Upgrade the latest version to get the fix.

The issue occurred when the hiring manager of a vacancy is deleted from the sysyem.
![fixedissue](https://user-images.githubusercontent.com/25813012/50680500-f31f5380-102d-11e9-8cd8-8bc2fb207816.png)

You could use the latest version which supports GDPR compliance as well.

**Comment by trongnghia203** [comment]
Dear @kavithagurusamy , thank you very much for your kind response. This helped a lot.
I tried another way to fix by logged-in to mysql, and updated the value of Hiring Manager ID in the table vacancy to an existing value Hiring Manager ID. Then, everything get back to work.

Thank you again,
Nghia
